CREATE OR REPLACE PROCEDURE public.sp_incrementalscd_sync_poitems()
 LANGUAGE plpgsql
AS $$
DECLARE
        sql          VARCHAR(MAX) := '';
        staged_record_count BIGINT :=0;
BEGIN

     -- Truncate staging table

    EXECUTE 'TRUNCATE TABLE sap_fabric_p2p_stg.lis_02_itm;';

    EXECUTE 'COPY JOB RUN auto_copy_po_items;';

    sql := 'SELECT COUNT(*) FROM sap_fabric_p2p_stg.lis_02_itm;';

    EXECUTE sql INTO staged_record_count;
    IF staged_record_count > 0 THEN
    -- When records found in the staging table
    -- Create staging table to store records from DM tables that match the current batch in the staging table
    EXECUTE 'drop table if exists temp_po_itmes_match;';
    EXECUTE 'create temp table temp_po_itmes_match(like sap_fabric_p2p_dm.po_items); ';

--Identify po doc item records from DM table that exist in the latest extract stg table
-- We will expire these records in a later step

    EXECUTE 'insert into temp_po_itmes_match (
                cancel_ind,
                purchasing_document_date,
                document_type,
                doc_category,
                posting_date_of_goods_received_or_invoice_receipt_for_order,
                purchasing_doc,
                purch_group,
                purchasing_org,
                local_currency,
                start_of_validity_period,
                end_of_validity_period,
                rec_supplier,
                supplier,
                invoicing_party,
                goods_supplier,
                logical_system,
                logical_system_orglogsy,
                supplying_plant,
                status,
                date_on_which_the_purchasing_document_was_entered,
                order_currency,
                exchange_rate,
                requisitioner,
                promotion,
                current_goods_receipt_quantity_in_order_unit,
                points_score_shipping_notif_gr_date__notified_date,
                number_of_deliveries,
                reason_for_ord,
                application_comp,
                transfer_process,
                item,
                deliv_compl,
                material,
                final_invoice,
                agreement,
                target_quantity,
                agreement_item,
                qty_deviation,
                item_counter,
                scheddeviation,
                points_score_shipping_notification,
                total_delivery_time_in_days,
                location,
                base_unit,
                variance_in_the_quantity_delivered_as_,
                material_group,
                material_matnr,
                order_unit,
                purchase_order_quantity,
                net_price,
                net_order_value_in_order_currency,
                price_unit,
                item_category,
                points_score_for_compliance_with_shipping_instructions,
                points_score_for_ontime_delivery,
                points_score_for_quantity_reliability,
                points_score_for_ontime_delivery_performance,
                points_score_for_quality_of_services,
                invoice_receipt,
                delivery_date_variance_in_days,
                short_text,
                denominator_for_conversion_of_order_unit_to_base_unit,
                numerator_for_conversion_of_order_unit_to_base_unit,
                grbased_iv,
                goods_receipt,
                plant,
                ers,
                target_value_for_outline_agreement_in_document_currency,
                fiyear_variant,
                interval_for_quantity_interval,
                interval_for_date_split,
                counter_for_date_split,
                counter_for_quantity_interval,
                counter_for_items,
                goods_supplier_pwlif,
                invoicing_party_prest,
                supplying_plant_pliwk,
                partnr_supplier,
                ordering_addr,
                smoothing_factor_quantity_variance,
                smoothing_factor_date_variance,
                best_score,
                smoothing_factor_compliance_with_shipping_instructions,
                "time",
                odq_changemode,
                odq_entitycntr,
                dm_record_start_date, 
                dm_record_end_date, 
                dm_is_current 
) 

select distinct

cancel_ind,
purchasing_document_date,
document_type,
doc_category,
posting_date_of_goods_received_or_invoice_receipt_for_order,
purchasing_doc,
purch_group,
purchasing_org,
local_currency,
start_of_validity_period,
end_of_validity_period,
rec_supplier,
supplier,
invoicing_party,
goods_supplier,
logical_system,
logical_system_orglogsy,
supplying_plant,
status,
date_on_which_the_purchasing_document_was_entered,
order_currency,
exchange_rate,
requisitioner,
promotion,
current_goods_receipt_quantity_in_order_unit,
points_score_shipping_notif_gr_date__notified_date,
number_of_deliveries,
reason_for_ord,
application_comp,
transfer_process,
item,
deliv_compl,
material,
final_invoice,
agreement,
target_quantity,
agreement_item,
qty_deviation,
item_counter,
scheddeviation,
points_score_shipping_notification,
total_delivery_time_in_days,
location,
base_unit,
variance_in_the_quantity_delivered_as_,
material_group,
material_matnr,
order_unit,
purchase_order_quantity,
net_price,
net_order_value_in_order_currency,
price_unit,
item_category,
points_score_for_compliance_with_shipping_instructions,
points_score_for_ontime_delivery,
points_score_for_quantity_reliability,
points_score_for_ontime_delivery_performance,
points_score_for_quality_of_services,
invoice_receipt,
delivery_date_variance_in_days,
short_text,
denominator_for_conversion_of_order_unit_to_base_unit,
numerator_for_conversion_of_order_unit_to_base_unit,
grbased_iv,
goods_receipt,
plant,
ers,
target_value_for_outline_agreement_in_document_currency,
fiyear_variant,
interval_for_quantity_interval,
interval_for_date_split,
counter_for_date_split,
counter_for_quantity_interval,
counter_for_items,
goods_supplier_pwlif,
invoicing_party_prest,
supplying_plant_pliwk,
partnr_supplier,
ordering_addr,
smoothing_factor_quantity_variance,
smoothing_factor_date_variance,
best_score,
smoothing_factor_compliance_with_shipping_instructions,
"time",
po.odq_changemode,
po.odq_entitycntr,
dm_record_start_date, 
dm_record_end_date,
dm_is_current
from 
    sap_fabric_p2p_dm.po_items po
  join
    sap_fabric_p2p_stg.lis_02_itm  stg
    on  (po.purchasing_doc = stg.ebeln) and (po.item = stg.ebelp)   
  where 
    dm_is_current = ''1''
;';

    sql := 'SELECT COUNT(*) FROM temp_po_itmes_match;';
    
    EXECUTE sql INTO staged_record_count;
    RAISE INFO 'Matched records into temp_po_itmes_match: %', staged_record_count;

    EXECUTE 'DELETE FROM sap_fabric_p2p_dm.po_items  
    using temp_po_itmes_match tpo
    WHERE   (sap_fabric_p2p_dm.po_items.purchasing_doc = tpo.purchasing_doc) and 
            (sap_fabric_p2p_dm.po_items.item = tpo.item) and 
            (sap_fabric_p2p_dm.po_items.dm_is_current =''1'');';

-- Insert all records from staging table into target table

EXECUTE 'insert into sap_fabric_p2p_dm.po_items
(
cancel_ind,
purchasing_document_date,
document_type,
doc_category,
posting_date_of_goods_received_or_invoice_receipt_for_order,
purchasing_doc,
purch_group,
purchasing_org,
local_currency,
start_of_validity_period,
end_of_validity_period,
rec_supplier,
supplier,
invoicing_party,
goods_supplier,
logical_system,
logical_system_orglogsy,
supplying_plant,
status,
date_on_which_the_purchasing_document_was_entered,
order_currency,
exchange_rate,
requisitioner,
promotion,
current_goods_receipt_quantity_in_order_unit,
points_score_shipping_notif_gr_date__notified_date,
number_of_deliveries,
reason_for_ord,
application_comp,
transfer_process,
item,
deliv_compl,
material,
final_invoice,
agreement,
target_quantity,
agreement_item,
qty_deviation,
item_counter,
scheddeviation,
points_score_shipping_notification,
total_delivery_time_in_days,
location,
base_unit,
variance_in_the_quantity_delivered_as_,
material_group,
material_matnr,
order_unit,
purchase_order_quantity,
net_price,
net_order_value_in_order_currency,
price_unit,
item_category,
points_score_for_compliance_with_shipping_instructions,
points_score_for_ontime_delivery,
points_score_for_quantity_reliability,
points_score_for_ontime_delivery_performance,
points_score_for_quality_of_services,
invoice_receipt,
delivery_date_variance_in_days,
short_text,
denominator_for_conversion_of_order_unit_to_base_unit,
numerator_for_conversion_of_order_unit_to_base_unit,
grbased_iv,
goods_receipt,
plant,
ers,
target_value_for_outline_agreement_in_document_currency,
fiyear_variant,
interval_for_quantity_interval,
interval_for_date_split,
counter_for_date_split,
counter_for_quantity_interval,
counter_for_items,
goods_supplier_pwlif,
invoicing_party_prest,
supplying_plant_pliwk,
partnr_supplier,
ordering_addr,
smoothing_factor_quantity_variance,
smoothing_factor_date_variance,
best_score,
smoothing_factor_compliance_with_shipping_instructions,
time,
odq_changemode,
odq_entitycntr,
dm_record_start_date, 
dm_record_end_date,
dm_is_current
) 

with po_items_latest as (select v.*,row_number() over (partition by ebeln,ebelp order by BEDAT ) as po_item_rank  
                            from sap_fabric_p2p_stg.lis_02_itm v  
                            where rocancel <> ''X'')

SELECT 

rocancel,
bedat,
bsart,
bstyp,
budat,
ebeln,
ekgrp,
ekorg,
hwaer,
kdatb,
kdate,
lblif,
lifnr,
lifre,
llief,
logsy,
orglogsy,
reswk,
statu,
sydat,
waers,
wkurs,
afnam,
aktnr,
aktwe,
alav,
alief,
bsgru,
bwapplnm,
bwvorg,
ebelp,
elikz,
ematn,
erekz,
konnr,
ktmng,
ktpnr,
kzmab,
kzpos,
kztab,
lavi,
lfzta,
lgort,
lmein,
mabw,
matkl,
matnr,
meins,
menge,
netpr,
netwr,
peinh,
pstyp,
pwev,
pwfr,
pwmt,
pwtt,
pwwe,
repos,
tabw,
txz01,
umren,
umrez,
webre,
wepos,
werks,
xersy,
zwert,
periv,
quan_int,
time_int,
notime,
noquan,
nopos,
pwlif,
prest,
pliwk,
plief,
pbest,
mgabw,
lfabw,
maxbw,
vvabw,
uzeit,
odq_changemode,
odq_entitycntr,
CURRENT_TIMESTAMP,
CASE WHEN (po_item_rank > 1 ) THEN current_timestamp else ''9999-12-31''::DATE  END, 
CASE WHEN (po_item_rank > 1 ) THEN ''0'' ELSE ''1'' END
FROM
po_items_latest;';

-- Insert Old records with expiry dates
    EXECUTE 'insert into sap_fabric_p2p_dm.po_items (
cancel_ind,
purchasing_document_date,
document_type,
doc_category,
posting_date_of_goods_received_or_invoice_receipt_for_order,
purchasing_doc,
purch_group,
purchasing_org,
local_currency,
start_of_validity_period,
end_of_validity_period,
rec_supplier,
supplier,
invoicing_party,
goods_supplier,
logical_system,
logical_system_orglogsy,
supplying_plant,
status,
date_on_which_the_purchasing_document_was_entered,
order_currency,
exchange_rate,
requisitioner,
promotion,
current_goods_receipt_quantity_in_order_unit,
points_score_shipping_notif_gr_date__notified_date,
number_of_deliveries,
reason_for_ord,
application_comp,
transfer_process,
item,
deliv_compl,
material,
final_invoice,
agreement,
target_quantity,
agreement_item,
qty_deviation,
item_counter,
scheddeviation,
points_score_shipping_notification,
total_delivery_time_in_days,
location,
base_unit,
variance_in_the_quantity_delivered_as_,
material_group,
material_matnr,
order_unit,
purchase_order_quantity,
net_price,
net_order_value_in_order_currency,
price_unit,
item_category,
points_score_for_compliance_with_shipping_instructions,
points_score_for_ontime_delivery,
points_score_for_quantity_reliability,
points_score_for_ontime_delivery_performance,
points_score_for_quality_of_services,
invoice_receipt,
delivery_date_variance_in_days,
short_text,
denominator_for_conversion_of_order_unit_to_base_unit,
numerator_for_conversion_of_order_unit_to_base_unit,
grbased_iv,
goods_receipt,
plant,
ers,
target_value_for_outline_agreement_in_document_currency,
fiyear_variant,
interval_for_quantity_interval,
interval_for_date_split,
counter_for_date_split,
counter_for_quantity_interval,
counter_for_items,
goods_supplier_pwlif,
invoicing_party_prest,
supplying_plant_pliwk,
partnr_supplier,
ordering_addr,
smoothing_factor_quantity_variance,
smoothing_factor_date_variance,
best_score,
smoothing_factor_compliance_with_shipping_instructions,
"time",
odq_changemode,
odq_entitycntr,
dm_record_start_date,
dm_record_end_date,
dm_is_current
) 
   
SELECT distinct 
cancel_ind,
purchasing_document_date,
document_type,
doc_category,
posting_date_of_goods_received_or_invoice_receipt_for_order,
purchasing_doc,
purch_group,
purchasing_org,
local_currency,
start_of_validity_period,
end_of_validity_period,
rec_supplier,
supplier,
invoicing_party,
goods_supplier,
logical_system,
logical_system_orglogsy,
supplying_plant,
status,
date_on_which_the_purchasing_document_was_entered,
order_currency,
exchange_rate,
requisitioner,
promotion,
current_goods_receipt_quantity_in_order_unit,
points_score_shipping_notif_gr_date__notified_date,
number_of_deliveries,
reason_for_ord,
application_comp,
transfer_process,
item,
deliv_compl,
material,
final_invoice,
agreement,
target_quantity,
agreement_item,
qty_deviation,
item_counter,
scheddeviation,
points_score_shipping_notification,
total_delivery_time_in_days,
location,
base_unit,
variance_in_the_quantity_delivered_as_,
material_group,
material_matnr,
order_unit,
purchase_order_quantity,
net_price,
net_order_value_in_order_currency,
price_unit,
item_category,
points_score_for_compliance_with_shipping_instructions,
points_score_for_ontime_delivery,
points_score_for_quantity_reliability,
points_score_for_ontime_delivery_performance,
points_score_for_quality_of_services,
invoice_receipt,
delivery_date_variance_in_days,
short_text,
denominator_for_conversion_of_order_unit_to_base_unit,
numerator_for_conversion_of_order_unit_to_base_unit,
grbased_iv,
goods_receipt,
plant,
ers,
target_value_for_outline_agreement_in_document_currency,
fiyear_variant,
interval_for_quantity_interval,
interval_for_date_split,
counter_for_date_split,
counter_for_quantity_interval,
counter_for_items,
goods_supplier_pwlif,
invoicing_party_prest,
supplying_plant_pliwk,
partnr_supplier,
ordering_addr,
smoothing_factor_quantity_variance,
smoothing_factor_date_variance,
best_score,
smoothing_factor_compliance_with_shipping_instructions,
"time",
odq_changemode,
odq_entitycntr,
dm_record_start_date,
current_timestamp,
''0'' 
FROM
    temp_po_itmes_match;';

ELSE
   RAISE INFO 'No data found in staging table.';

END IF; 

-- Refresh dm.billing_document_item_latest MV. This MV will be used to list the latest version of the billing_document_items

EXECUTE 'refresh materialized view sap_fabric_p2p_adm.po_items_latest;';
END
$$
