CREATE OR REPLACE PROCEDURE public.sp_incremental_sync_material_attr()
 LANGUAGE plpgsql
AS $$
DECLARE
        sql          VARCHAR(MAX) := '';
        staged_record_count BIGINT :=0;
BEGIN

     -- Truncate staging table

    EXECUTE 'TRUNCATE TABLE sap_fabric_p2p_stg.material_attr;';

    EXECUTE 'COPY JOB RUN auto_copy_material_attr';

--Execute MERGE on primary key to update and overwrite new/updated records

EXECUTE 'MERGE INTO sap_fabric_p2p_dm.material_attr
                USING sap_fabric_p2p_stg.material_attr stg 
                on (sap_fabric_p2p_dm.material_attr.material = stg.matnr)
WHEN MATCHED THEN UPDATE SET
                created_on = stg.ersda,
                created_by = stg.ernam,
                last_change = stg.laeda,
                changed_by = stg.aenam,
                complete_status = stg.vpsta,
                maint_status = stg.pstat,
                df_client_level = stg.lvorm,
                material_type = stg.mtart,
                industry_sector = stg.mbrsh,
                material_group = stg.matkl,
                old_matl_number = stg.bismt,
                base_unit = stg.meins,
                order_unit = stg.bstme,
                document = stg.zeinr,
                document_type = stg.zeiar,
                doc_version = stg.zeivr,
                page_format = stg.zeifo,
                doc_change_no = stg.aeszn,
                page_number = stg.blatt,
                no_of_sheets = stg.blanz,
                prodinspmemo = stg.ferth,
                page_format_formt = stg.formt,
                sizedimensions = stg.groes,
                basic_material = stg.wrkst,
                ind_std_desc = stg.normt,
                laboffice = stg.labor,
                purchvalue_key = stg.ekwsl,
                gross_weight = stg.brgew,
                net_weight = stg.ntgew,
                unit_of_weight = stg.gewei,
                volume = stg.volum,
                volume_unit = stg.voleh,
                container = stg.behvo,
                storconditions = stg.raube,
                temperature = stg.tempb,
                lowlevel_code = stg.disst,
                trans_group = stg.tragr,
                haz_matl_no = stg.stoff,
                division = stg.spart,
                competitor = stg.kunnr,
                ean_number = stg.eannr,
                quantity_number_of_grgi_slips_to_be_printed = stg.wesch,
                procure_rule = stg.bwvor,
                supply_source = stg.bwscl,
                season = stg.saiso,
                label_type = stg.etiar,
                label_form = stg.etifo,
                disposal_type = stg.entar,
                eanupc = stg.ean11,
                ean_category = stg.numtp,
                length = stg.laeng,
                width = stg.breit,
                height = stg.hoehe,
                unit = stg.meabm,
                prod_hierarchy = stg.prdha,
                net_change_cstg = stg.aeklk,
                cad_indicator = stg.cadkz,
                qm_procurement = stg.qmpur,
                allowed_packaging_weight = stg.ergew,
                unit_of_weight_ergei = stg.ergei,
                allowed_packaging_volume = stg.ervol,
                volume_unit_ervoe = stg.ervoe,
                excess_weight_tolerance_for_handling_unit = stg.gewto,
                excess_volume_tolerance_of_the_handling_unit = stg.volto,
                var_order_unit = stg.vabme,
                revision_level = stg.kzrev,
                configurable = stg.kzkfg,
                batch_mgmt_rqt = stg.xchpf,
                packagmattype = stg.vhart,
                maximum_level_by_volume = stg.fuelg,
                stacking_factor = stg.stfak,
                matl_grp_pckmat = stg.magrv,
                authorizgroup = stg.begru,
                valid_from = stg.datab,
                valid_to = stg.liqdt,
                season_year = stg.saisj,
                price_band_cat = stg.plgtp,
                w_empties_bom = stg.mlgut,
                ext_matl_group = stg.extwg,
                crossplant_cm = stg.satnr,
                matl_category = stg.attyp,
                coproduct = stg.kzkup,
                followup_matl = stg.kznfm,
                pr_ref_matl = stg.pmata,
                xplant_status = stg.mstae,
                xdchain_status = stg.mstav,
                valid_from_mstde = stg.mstde,
                valid_from_mstdv = stg.mstdv,
                tax_class = stg.taklv,
                catalog_profile = stg.rbnrm,
                minimum_remaining_shelf_life = stg.mhdrz,
                total_shelf_life = stg.mhdhb,
                storage_percentage = stg.mhdlp,
                content_unit = stg.inhme,
                net_contents = stg.inhal,
                comparison_price_unit = stg.vpreh,
                labelmatl_grpg = stg.etiag,
                gross_contents = stg.inhbr,
                conv_method = stg.cmeth,
                int_object_no = stg.cuobf,
                envt_relevant = stg.kzumw,
                prodallocation = stg.kosch,
                pricing_profile = stg.sprof,
                disc_in_kind = stg.nrfhg,
                mfr_part_number = stg.mfrpn,
                manufacturer = stg.mfrnr,
                int_material_no = stg.bmatn,
                mfr_part_profile = stg.mprof,
                units_meas_use = stg.kzwsm,
                rollout = stg.saity,
                dgindprofile = stg.profl,
                highly_viscous = stg.ihivi,
                in_bulkliquid = stg.iloos,
                serializlevel = stg.serlv,
                closed = stg.kzgvh,
                batch_rec_req = stg.xgchp,
                assigneffvals = stg.kzeff,
                comp_level = stg.compl,
                period_ind = stg.iprkz,
                rounding_rule = stg.rdmhd,
                prodcomposition = stg.przus,
                genitemcatgroup = stg.mtpos_mara,
                log_variants = stg.bflme,
                cw_material = stg.xcwmat,
                valuation_uom = stg.valum,
                tolerance_group = stg.tolgr,
                checkbox = stg.tara,
                base_unit_tarum = stg.tarum,
                nsn = stg.nsnid,
                internal_char = stg.color_atinn,
                internal_char_size1_atinn = stg.size1_atinn,
                internal_char_size2_atinn = stg.size2_atinn,
                color = stg.color,
                main_size = stg.size1,
                second_size = stg.size2,
                char_value = stg.free_char,
                care_code = stg.care_code,
                brand = stg.brand_id,
                component_1 = stg.fiber_code1,
                perc_share_1 = stg.fiber_part1,
                component_2 = stg.fiber_code2,
                perc_share_2 = stg.fiber_part2,
                component_3 = stg.fiber_code3,
                perc_share_3 = stg.fiber_part3,
                component_4 = stg.fiber_code4,
                perc_share_4 = stg.fiber_part4,
                mg_hierarchy_level = stg.rpa_wgh1,
                mg_hierarchy_level_rpa_wgh2 = stg.rpa_wgh2,
                mg_hierarchy_level_rpa_wgh3 = stg.rpa_wgh3,
                mg_hierarchy_level_rpa_wgh4 = stg.rpa_wgh4,
                fashion_grade = stg.fashgrd,
                odq_changemode = stg.odq_changemode,
                odq_entitycntr = stg.odq_entitycntr
WHEN NOT MATCHED THEN
    INSERT (material,
            created_on,
            created_by,
            last_change,
            changed_by,
            complete_status,
            maint_status,
            df_client_level,
            material_type,
            industry_sector,
            material_group,
            old_matl_number,
            base_unit,
            order_unit,
            document,
            document_type,
            doc_version,
            page_format,
            doc_change_no,
            page_number,
            no_of_sheets,
            prodinspmemo,
            page_format_formt,
            sizedimensions,
            basic_material,
            ind_std_desc,
            laboffice,
            purchvalue_key,
            gross_weight,
            net_weight,
            unit_of_weight,
            volume,
            volume_unit,
            container,
            storconditions,
            temperature,
            lowlevel_code,
            trans_group,
            haz_matl_no,
            division,
            competitor,
            ean_number,
            quantity_number_of_grgi_slips_to_be_printed,
            procure_rule,
            supply_source,
            season,
            label_type,
            label_form,
            disposal_type,
            eanupc,
            ean_category,
            length,
            width,
            height,
            unit,
            prod_hierarchy,
            net_change_cstg,
            cad_indicator,
            qm_procurement,
            allowed_packaging_weight,
            unit_of_weight_ergei,
            allowed_packaging_volume,
            volume_unit_ervoe,
            excess_weight_tolerance_for_handling_unit,
            excess_volume_tolerance_of_the_handling_unit,
            var_order_unit,
            revision_level,
            configurable,
            batch_mgmt_rqt,
            packagmattype,
            maximum_level_by_volume,
            stacking_factor,
            matl_grp_pckmat,
            authorizgroup,
            valid_from,
            valid_to,
            season_year,
            price_band_cat,
            w_empties_bom,
            ext_matl_group,
            crossplant_cm,
            matl_category,
            coproduct,
            followup_matl,
            pr_ref_matl,
            xplant_status,
            xdchain_status,
            valid_from_mstde,
            valid_from_mstdv,
            tax_class,
            catalog_profile,
            minimum_remaining_shelf_life,
            total_shelf_life,
            storage_percentage,
            content_unit,
            net_contents,
            comparison_price_unit,
            labelmatl_grpg,
            gross_contents,
            conv_method,
            int_object_no,
            envt_relevant,
            prodallocation,
            pricing_profile,
            disc_in_kind,
            mfr_part_number,
            manufacturer,
            int_material_no,
            mfr_part_profile,
            units_meas_use,
            rollout,
            dgindprofile,
            highly_viscous,
            in_bulkliquid,
            serializlevel,
            closed,
            batch_rec_req,
            assigneffvals,
            comp_level,
            period_ind,
            rounding_rule,
            prodcomposition,
            genitemcatgroup,
            log_variants,
            cw_material,
            valuation_uom,
            tolerance_group,
            checkbox,
            base_unit_tarum,
            nsn,
            internal_char,
            internal_char_size1_atinn,
            internal_char_size2_atinn,
            color,
            main_size,
            second_size,
            char_value,
            care_code,
            brand,
            component_1,
            perc_share_1,
            component_2,
            perc_share_2,
            component_3,
            perc_share_3,
            component_4,
            perc_share_4,
            mg_hierarchy_level,
            mg_hierarchy_level_rpa_wgh2,
            mg_hierarchy_level_rpa_wgh3,
            mg_hierarchy_level_rpa_wgh4,
            fashion_grade,
            odq_changemode,
            odq_entitycntr
)
    VALUES (
            stg.matnr,
            stg.ersda,
            stg.ernam,
            stg.laeda,
            stg.aenam,
            stg.vpsta,
            stg.pstat,
            stg.lvorm,
            stg.mtart,
            stg.mbrsh,
            stg.matkl,
            stg.bismt,
            stg.meins,
            stg.bstme,
            stg.zeinr,
            stg.zeiar,
            stg.zeivr,
            stg.zeifo,
            stg.aeszn,
            stg.blatt,
            stg.blanz,
            stg.ferth,
            stg.formt,
            stg.groes,
            stg.wrkst,
            stg.normt,
            stg.labor,
            stg.ekwsl,
            stg.brgew,
            stg.ntgew,
            stg.gewei,
            stg.volum,
            stg.voleh,
            stg.behvo,
            stg.raube,
            stg.tempb,
            stg.disst,
            stg.tragr,
            stg.stoff,
            stg.spart,
            stg.kunnr,
            stg.eannr,
            stg.wesch,
            stg.bwvor,
            stg.bwscl,
            stg.saiso,
            stg.etiar,
            stg.etifo,
            stg.entar,
            stg.ean11,
            stg.numtp,
            stg.laeng,
            stg.breit,
            stg.hoehe,
            stg.meabm,
            stg.prdha,
            stg.aeklk,
            stg.cadkz,
            stg.qmpur,
            stg.ergew,
            stg.ergei,
            stg.ervol,
            stg.ervoe,
            stg.gewto,
            stg.volto,
            stg.vabme,
            stg.kzrev,
            stg.kzkfg,
            stg.xchpf,
            stg.vhart,
            stg.fuelg,
            stg.stfak,
            stg.magrv,
            stg.begru,
            stg.datab,
            stg.liqdt,
            stg.saisj,
            stg.plgtp,
            stg.mlgut,
            stg.extwg,
            stg.satnr,
            stg.attyp,
            stg.kzkup,
            stg.kznfm,
            stg.pmata,
            stg.mstae,
            stg.mstav,
            stg.mstde,
            stg.mstdv,
            stg.taklv,
            stg.rbnrm,
            stg.mhdrz,
            stg.mhdhb,
            stg.mhdlp,
            stg.inhme,
            stg.inhal,
            stg.vpreh,
            stg.etiag,
            stg.inhbr,
            stg.cmeth,
            stg.cuobf,
            stg.kzumw,
            stg.kosch,
            stg.sprof,
            stg.nrfhg,
            stg.mfrpn,
            stg.mfrnr,
            stg.bmatn,
            stg.mprof,
            stg.kzwsm,
            stg.saity,
            stg.profl,
            stg.ihivi,
            stg.iloos,
            stg.serlv,
            stg.kzgvh,
            stg.xgchp,
            stg.kzeff,
            stg.compl,
            stg.iprkz,
            stg.rdmhd,
            stg.przus,
            stg.mtpos_mara,
            stg.bflme,
            stg.xcwmat,
            stg.valum,
            stg.tolgr,
            stg.tara,
            stg.tarum,
            stg.nsnid,
            stg.color_atinn,
            stg.size1_atinn,
            stg.size2_atinn,
            stg.color,
            stg.size1,
            stg.size2,
            stg.free_char,
            stg.care_code,
            stg.brand_id,
            stg.fiber_code1,
            stg.fiber_part1,
            stg.fiber_code2,
            stg.fiber_part2,
            stg.fiber_code3,
            stg.fiber_part3,
            stg.fiber_code4,
            stg.fiber_part4,
            stg.rpa_wgh1,
            stg.rpa_wgh2,
            stg.rpa_wgh3,
            stg.rpa_wgh4,
            stg.fashgrd,
            stg.odq_changemode,
            stg.odq_entitycntr
    );';
 


END
$$