AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Helping customers break down data silos with AWS Integration services

##  To use this template, you must have installed the below extractors and created their service as per pre-requisites.  Once you have, simply find and replace the service details for each 
##  By default this schedules the below flows to run every five minutes
##  2LIS_11_VAHDR  - /sap/opu/odata/sap/ZSALES_ORDERS_HEADER_SRV/EntityOf2LIS_11_VAHDR 
##  2LIS_11_VAITM  - /sap/opu/odata/sap/ZSALES_ORDERS_ITEMS_SRV/EntityOf2LIS_11_VAITM 
##  2LIS_12_VCHDR  - /sap/opu/odata/sap/ZDELIVERY_HEADER_SRV/EntityOf2LIS_12_VCHD
##  2LIS_12_VCITM  - /sap/opu/odata/sap/ZDELIVERY_ITEMS_SRV/EntityOf2LIS_12_VCITM
##  2LIS_13_VDHDR  - /sap/opu/odata/sap/ZBILL_DOCS_HEADER_SRV/EntityOf2LIS_13_VDHDR
##  2LIS_13_VDITM  - /sap/opu/odata/sap/ZBILL_DOCS_ITEMS_SRV/EntityOf2LIS_13_VDITM

Parameters:
  ConnectionName:
    Description: The name of the SAP source system connection
    Type: String

  AppFlowSAPStartTime: 
    Description: EPOC date of first run for flow
    Type: Number

  DestinationS3BucketName: 
    Description: Name of the Destination S3 Bucket
    Type: String

  DestinationS3BucketPrefix:
    Description: Prefix in the Destination S3 Bucket (Optional)
    Type: String

  SalesOrdersHeader:
    Description: Object path for SalesOrderHeadertoS3 extractor OData Service
    Type: String
    Default: /sap/opu/odata/sap/ZSALES_ORDERS_HEADER_SRV/EntityOf2LIS_11_VAHDR

  SalesOrdersItems:
    Description: Object path for SalesOrderItemstoS3 extractor OData Service
    Type: String
    Default: /sap/opu/odata/sap/ZSALES_ORDERS_ITEMS_SRV/EntityOf2LIS_11_VAITM

  DeliveryHeader:
    Description: Object path for DeliveryHeadertoS3 extractor OData Service
    Type: String
    Default: /sap/opu/odata/sap/ZDELIVERY_HEADER_SRV/EntityOf2LIS_12_VCHDR
  
  DeliveryItems:
    Description: Object path for DeliveryItemstoS3 extractor OData Service
    Type: String
    Default: /sap/opu/odata/sap/ZDELIVERY_ITEMS_SRV/EntityOf2LIS_12_VCITM

  BillingDocumentHeader:
    Description: Object path for BillingDocumentHeadertoS3 extractor OData Service
    Type: String
    Default: /sap/opu/odata/sap/ZBILL_DOCS_HEADER_SRV/EntityOf2LIS_13_VDHDR

  BillingDocumentItems:
    Description: Object path for BillingDocumentItemstoS3 extractor OData Service
    Type: String
    Default: /sap/opu/odata/sap/ZBILL_DOCS_ITEMS_SRV/EntityOf2LIS_13_VDITM

Resources: 
  # Sales Order Header
  SalesOrderHeadertoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: sales_order_header
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_11_VAHDR Sales Order Header'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectionName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            ObjectPath: !Ref SalesOrdersHeader  
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            BucketPrefix: !Ref DestinationS3BucketPrefix
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP 
          
  # Sales Order Items
  SalesOrderItemstoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: sales_order_item
      FlowStatus: Active
      Description: 'Pull data from SAP and saves into S3 for 2LIS_11_VAITM Sales Order Items'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectionName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            ObjectPath: !Ref SalesOrdersItems
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            BucketPrefix: !Ref DestinationS3BucketPrefix
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP        
  
  # Delivery Header
  DeliveryHeadertoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: delivery_header
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_12_VCHDR Delivery Header'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectionName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            ObjectPath: !Ref DeliveryHeader
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            BucketPrefix: !Ref DestinationS3BucketPrefix
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP
     
  # Delivery Items
  DeliveryItemstoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: delivery_item
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_12_VCITM Delivery Items'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectionName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            ObjectPath: !Ref DeliveryItems 
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            BucketPrefix: !Ref DestinationS3BucketPrefix
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP

  # Billing Document Header
  BillingDocumentHeadertoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: billing_document_header
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_13_VDHDR Invoice Header'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectionName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            ObjectPath: !Ref BillingDocumentHeader
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            BucketPrefix: !Ref DestinationS3BucketPrefix
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP        
  
  # Billing Document Items
  BillingDocumentItemstoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: billing_document_item
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_13_VDITM Invoice Item'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectionName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            ObjectPath: !Ref BillingDocumentItems
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            BucketPrefix: !Ref DestinationS3BucketPrefix
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP

                               