AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Helping customers break down data silos with AWS Integration services

##  To use this template, you must have installed the below extractors and created their service as per pre-requisites.  Once you have, simply find and replace the service details for each 
##  By default this schedules the below flows to run every five minutes
##  2LIS_02_ITM  - /sap/opu/odata/sap/ZPO_ITEMS_SRV/EntityOf2LIS_02_ITM
##  2LIS_06_INV  - /sap/opu/odata/sap/ZSUPPLIER_INVOICES_SRV/EntityOf2LIS_06_INV


Parameters:
  ConnectorName:
    Description: The name of the SAP source system connection
    Type: String

  AppFlowSAPStartTime: 
    Description: EPOC date of first run for flow
    Type: Number

  DestinationS3BucketName: 
    Description: Name of the Destination S3 Bucket
    Type: String
  
  DestinationS3BucketPrefix:
    Description: Prefix in the Destination S3 Bucket (Optional)
    Type: String

  PurchaseOrderItems:
    Description: Object path for PurchaseOrderItemstoS3 extractor OData Service
    Type: String
    Default: /sap/opu/odata/sap/ZPO_ITEMS_SRV/EntityOf2LIS_02_ITM

  SupplierInvoices:
    Description: Object path for SupplierInvoicestoS3 extractor OData Service
    Type: String
    Default: /sap/opu/odata/sap/ZSUPPLIER_INVOICES_SRV/EntityOf2LIS_06_INV


Resources: 
  # Purchase Order Items
  PurchaseOrderItemstoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: po_items
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_02_ITM PO items'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            ObjectPath: !Ref PurchaseOrderItems
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            BucketPrefix: !Ref DestinationS3BucketPrefix
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP
          
  # Supplier Invoices
  SupplierInvoicestoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: supplier_invoices
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_06_INV Supplier Invoice'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            ObjectPath: !Ref SupplierInvoices
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            BucketPrefix: !Ref DestinationS3BucketPrefix
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP       